version: '3.7'
services:

  discovery:
    container_name: discovery-server
    image: steeltoeoss/eureka-server
    ports:
      - "8761:8761"

  config:
    container_name: config-server
    image: steeltoeoss/config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config:/config
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: "file:///config"

  auth:
    container_name: auth-server
    image: eclipse-temurin:21
    ports:
      - "9000:9000"
    volumes:
      - ./spring-cloud-gateway:/app
    command: ["java", "-jar", "/app/tanzu-local-authorization-server-beta4.jar"]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000" ]
      interval: 3s
      timeout: 10s
      retries: 5

  gateway:
    container_name: gateway-server
    image: eclipse-temurin:21
    ports:
      - "8090:8090"
    volumes:
      - ./spring-cloud-gateway:/app
    working_dir: /app
    command: [ "bash", "./run.sh" ]
    depends_on:
      auth:
        condition: service_healthy
    links:
      - auth
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_SSO_ISSUER_URI: http://auth:9000
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_SSO_AUTHORIZATION_URI: http://localhost:9000/oauth2/authorize
