version: '3.7'
services:

  discovery:
    container_name: discovery-server
    image: steeltoeoss/eureka-server
    ports:
      - "8761:8761"

  config:
    container_name: config-server
    image: steeltoeoss/config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config:/config
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: "file:///config"

  gateway-auth:
    container_name: gateway-and-auth-servers
    image: eclipse-temurin:21
    ports:
      - "8090:8090"
      - "9000:9000"
    volumes:
      - ./spring-enterprise:/app
    working_dir: /app
    command: [ "bash", "./run.sh" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
