
management:
  endpoints:
    web:
      exposure:
        include: info,health
spring:
  ai:
    openai:
      api-key: "YOUR KEY"
    vectorstore:
      pgvector: 
        initialize-schema: true
        remove-existing-vector-store-table: true
  application:
    name: acme-assist
  cloud:
    config:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: rootpassword
    url: jdbc:postgresql://localhost:5433/acme-assist
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect